arch: arm64

dist: xenial
language: go

go:
- 1.11.x

services:
- docker

addons:
  apt:
    update: true

before_script:
- "echo commit: $TRAVIS_COMMIT"
- "echo tag: $TRAVIS_TAG"
- "echo branch: $TRAVIS_BRANCH"
- "echo build: $TRAVIS_BUILD_NUMBER"

jobs:
  include:
    - stage: docker
      name: "pimba/mopidy docker image build & publication"
      script:
      - make build
      - docker images
      - |
        if [ "$TRAVIS_BRANCH" = master ]; then
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          make push
        fi
